[install]
exact = true
frozen = false
trust = true

[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageSkipTestFiles = true
coverageExclude = [
  "node_modules/**",
  "dist/**",
  "scripts/**",
  "**/*.spec.ts",
  "**/*.test.ts",
  "tests/**"
]
coverageThreshold = { lines = 0.75, functions = 0.8, statements = 0.75 }
concurrent = true
maxConcurrency = 20
